package au.csiro.data.recsys.model;

// Generated 09/02/2017 5:17:21 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Collection generated by hbm2java
 */
@Entity
@Table(name = "collection", schema = "public")
public class Collection implements java.io.Serializable {

	private long collectionId;
	private String collectionName;
	private Date dateCreated;
	private Set<Dataset> datasets = new HashSet<Dataset>(0);

	public Collection() {
	}

	public Collection(long collectionId, String collectionName, Date dateCreated) {
		this.collectionId = collectionId;
		this.collectionName = collectionName;
		this.dateCreated = dateCreated;
	}

	public Collection(long collectionId, String collectionName, Date dateCreated, Set<Dataset> datasets) {
		this.collectionId = collectionId;
		this.collectionName = collectionName;
		this.dateCreated = dateCreated;
		this.datasets = datasets;
	}

	@Id
	@Column(name = "collection_id", unique = true, nullable = false)
	public long getCollectionId() {
		return this.collectionId;
	}

	public void setCollectionId(long collectionId) {
		this.collectionId = collectionId;
	}

	@Column(name = "collection_name", nullable = false)
	public String getCollectionName() {
		return this.collectionName;
	}

	public void setCollectionName(String collectionName) {
		this.collectionName = collectionName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_created", nullable = false, length = 13)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "collection")
	public Set<Dataset> getDatasets() {
		return this.datasets;
	}

	public void setDatasets(Set<Dataset> datasets) {
		this.datasets = datasets;
	}

}
