package au.csiro.data.recsys.model;

// Generated 09/02/2017 5:17:21 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RelatedDataset generated by hbm2java
 */
@Entity
@Table(name = "related_dataset", schema = "public")
public class RelatedDataset implements java.io.Serializable {

	private long relatedId;
	private Dataset dataset;
	private String fedoraId;
	private String title;
	private String landingpage;
	private Integer rank;
	private double simValue;
	private Set<Results> resultses = new HashSet<Results>(0);

	public RelatedDataset() {
	}

	public RelatedDataset(long relatedId, Dataset dataset, String fedoraId, String title, String landingpage,
			double simValue) {
		this.relatedId = relatedId;
		this.dataset = dataset;
		this.fedoraId = fedoraId;
		this.title = title;
		this.landingpage = landingpage;
		this.simValue = simValue;
	}

	public RelatedDataset(long relatedId, Dataset dataset, String fedoraId, String title, String landingpage,
			Integer rank, double simValue, Set<Results> resultses) {
		this.relatedId = relatedId;
		this.dataset = dataset;
		this.fedoraId = fedoraId;
		this.title = title;
		this.landingpage = landingpage;
		this.rank = rank;
		this.simValue = simValue;
		this.resultses = resultses;
	}

	@Id
	@Column(name = "related_id", unique = true, nullable = false)
	public long getRelatedId() {
		return this.relatedId;
	}

	public void setRelatedId(long relatedId) {
		this.relatedId = relatedId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "target", nullable = false,referencedColumnName = "fedora_id")
	public Dataset getDataset() {
		return this.dataset;
	}

	public void setDataset(Dataset dataset) {
		this.dataset = dataset;
	}

	@Column(name = "fedora_id", nullable = false)
	public String getFedoraId() {
		return this.fedoraId;
	}

	public void setFedoraId(String fedoraId) {
		this.fedoraId = fedoraId;
	}

	@Column(name = "title", nullable = false)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "landingpage", nullable = false)
	public String getLandingpage() {
		return this.landingpage;
	}

	public void setLandingpage(String landingpage) {
		this.landingpage = landingpage;
	}

	@Column(name = "rank")
	public Integer getRank() {
		return this.rank;
	}

	public void setRank(Integer rank) {
		this.rank = rank;
	}

	@Column(name = "sim_value", nullable = false, precision = 17, scale = 17)
	public double getSimValue() {
		return this.simValue;
	}

	public void setSimValue(double simValue) {
		this.simValue = simValue;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "relatedDataset")
	public Set<Results> getResultses() {
		return this.resultses;
	}

	public void setResultses(Set<Results> resultses) {
		this.resultses = resultses;
	}

}
